# We are making this configuration here, because if there would be more environments for this microservice to be ran on it would be easier for uss. Also for better manage the API versioning.
spring:
    profiles:
        active: local # By default local is activated.
    application:
        name: country-service-backend
restClient:
    countriesNowUrl: https://countriesnow.space/api/v0.1/countries/
---
spring:
    config:
        activate:
            on-profile: 
                - non-prod # If profile is non-prod, use what inside these ones.
---
# Different env prod
---
